#!/bin/bash

afl-g++ "$@"
for file in $(find . -name "*.o"); do
    for section in $(readelf -W -S $file | grep .rodata | awk -F ']' '{print $2}' | awk '{print $1}'); do
        new_section=".text.$(echo -n "$file$section" | md5sum | awk '{print $1}')"
        objcopy --set-section-flags $section=contents,alloc,load,readonly,code --rename-section $section=$new_section $file
    done
done
